apiVersion: v1
kind: Secret
metadata:
  name: arturo-secrets
  namespace: arturo
type: Opaque
stringData:
  POSTGRES_DB: arturo
  POSTGRES_USER: arturo
  POSTGRES_PASSWORD: change_me
  MINIO_ROOT_USER: arturo
  MINIO_ROOT_PASSWORD: change_me
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: change_me
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: change_me
